name: emi_manager
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.2.6

dependencies:
  collection: ^1.17.0
  csv: ^6.0.0
  currency_picker: ^2.0.21
  device_info_plus: ^11.1.1
  file_picker: ^8.1.4
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  go_router: null
  hive_flutter: ^1.1.0
  intl: null
  lottie: ^2.7.0
  onboarding: ^4.0.2
  open_file: ^3.5.9
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  riverpod_annotation: null
  share_plus: ^10.1.2
  showcaseview: ^3.0.0
  uuid: null
  http: ^1.2.1
  shared_preferences: ^2.3.4
  flutter_markdown: ^0.6.18
  version: ^3.0.2

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  go_router_builder: null
  hive_generator: ^2.0.1
  riverpod_generator: ^2.4.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/animations/
